services:
  db:
    image: mariadb:10.10
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent'
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3306:3306
      - 33060:33060
    # expose:
    #   - 3306
    #   - 33060
    networks:
      - backnet
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: backend
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 8000:8000
    # expose:
    #   - 8000
    networks:
      - backnet
      - frontnet
    environment:
      # set database, memcached etc credentials
      DB_HOST: db
      DB_NAME: example
      DB_USER: root
      DB_PASSWORD: db-78n9n
    depends_on:
      db:
        condition: service_healthy

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - frontnet

volumes:
  db-data:


secrets:
  db-password:
    file: db-password.txt

networks:
  backnet:
  frontnet:
